---
title: "CropingByMeanIntensity"
author: "H Desgrez Dautet"
date: "2023-04-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
wd = normalizePath(choose.dir())
knitr::opts_knit$set(root.dir = wd)
```


```{r param}
slicesByNucleus <- 10
```

### Récupération des données
```{r import}
titlesAndSlices <- read.csv(file = "meanBySlices.csv",header=TRUE,sep=';',dec='.')
meanBlue <- read.csv(file = "TmeanBlue4crop.csv",header=FALSE,sep=';',dec='.')
meanRed <- read.csv(file = "TmeanBlue4crop.csv",header=FALSE,sep=';',dec='.')
outBlue <- file("cropBlue.csv","w")
outRed <- file("cropRed.csv","w")
```

### Réunion des données
```{r merge}
dfBlue <- data.frame(titlesAndSlices,t(meanBlue))
dfRed <- data.frame(titlesAndSlices,t(meanRed))
```

### Fonctions
```{r function}
indexMinSlices <- function (arr, out){
  size <- length(arr)
  if (out==0) return (c(1,size))
  
  cptBas <- 1
  cptHaut <- size
  
  i <- 0
  while (i < out){
    if (arr[[cptBas]] < arr[[cptHaut]])
      cptBas <- cptBas+1
    else if (arr[[cptBas]] >= arr[[cptHaut]])
      cptHaut <- cptHaut-1
    i <- i+1
  }
  return (c(cptBas,cptHaut))
}


cropB <- function(ligne){
  title <- ligne[1]
  slices <- as.integer(ligne[2])
  
  slicesLeft <- slices %% slicesByNucleus
  
  means <- lapply(ligne[1:slices+2],as.integer)
  
  minMax <- indexMinSlices(means,slicesLeft)
  out4csv <- paste(title,slices,minMax[1],minMax[2], sep = ";")
  writeLines(out4csv, outBlue)
}

cropR <- function(ligne){
  title <- ligne[1]
  slices <- as.integer(ligne[2])
  
  slicesLeft <- slices %% slicesByNucleus
  
  means <- apply(ligne[1:slices+2],as.integer)
  
  minMax <- indexMinSlices(means,slicesLeft)
  
  out4csv <- paste(title,slices,minMax[1],minMax[2], sep = ";")
  writeLines(out4csv, outRed)
}
```

### Traitement
```{r traitement}
write("title;slices;min;max", outBlue, append = FALSE)
# write("title;slices;min;max", outRed, append = FALSE)

apply(dfBlue, 1, cropB)
# apply(dfRed, 1, cropR)
```

```{r clear}
close(outBlue)
close(outRed)
```



### Test pour bon fonctionnement
```{r test}
t1 <- c(1,2,3,4,5,6,7,8,9,10)
t2 <- c(1,3,9,4,5,6,7,8,10,2)
t3 <- c(3,2,10,4,5,6,7,8,1,2)

r1 <- indexMinSlices(na.omit(t1),3)
r2 <- indexMinSlices(na.omit(t2),3)
r3 <- indexMinSlices(na.omit(t3),3)
cat("res1=",r1,"res2=",r2,"res3=",r3)

# write.csv("test", outputBlue, append = TRUE, sep=';', row.names = FALSE, col.names = FALSE)
```
