---
title: "CropingByMeanIntensity"
author: "H Desgrez Dautet"
date: "2023-04-14"
output: html_document
---

```{r library}
library(ggplot2)
library(ggridges)
library(tidyr)
library(scales)
library(egg)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
wd = choose.dir()
knitr::opts_knit$set(root.dir = wd)
slicesByNucleus <- 10
```

### Récupération des données

```{r import}
titlesAndSlices <- read.csv(file = "meanBySlices.csv",header=TRUE,sep=";",dec=".")
meanBlue <- read.csv(file = "TmeanBlue4crop.csv",header=FALSE,sep=";",dec=".")
#meanRed <- read.csv(file = "TmeanRed4crop.csv",header=FALSE,sep=';',dec='.')
outBlue <- file("cropBlue2.csv","w")
# outRed <- file("cropRed.csv","w")
```

### Réunion des données

```{r merge}
dfBlue <- data.frame(titlesAndSlices,t(meanBlue))
#dfRed <- data.frame(titlesAndSlices,t(meanRed))
```

### Fonctions

```{r function}
indexMinSlices <- function (arr, out){
  size <- length(arr)
  if (out==0) return (c(1,size))
  
  cptBas <- 1
  cptHaut <- size
  
  i <- 0
  while (i < out){
    if (arr[[cptBas]] < arr[[cptHaut]]) cptBas <- cptBas+1
    else if (arr[[cptBas]] >= arr[[cptHaut]]) cptHaut <- cptHaut-1
    i <- i+1
  }
  return (c(cptBas,cptHaut))
}


cropB <- function(ligne){
  title <- ligne[1]
  slices <- as.integer(ligne[2])
  
  slicesLeft <- slices %% slicesByNucleus
  # \v/ only for minus one proj \v/
  # if (slices > 19) slicesLeft <- slicesLeft +10
  
  means <- lapply(ligne[1:slices+2],as.integer)
  
  minMax <- indexMinSlices(means,slicesLeft)
  out4csv <- paste(title,slices,minMax[1],minMax[2], sep = ";")
  writeLines(out4csv, outBlue)
  #return(minMax)
}

cropR <- function(ligne){
  title <- ligne[1]
  slices <- as.integer(ligne[2])
  
  slicesLeft <- slices %% slicesByNucleus
  
  means <- apply(ligne[1:slices+2],as.integer)
  
  minMax <- indexMinSlices(means,slicesLeft)
  
  out4csv <- paste(title,slices,minMax[1],minMax[2], sep = ";")
  writeLines(out4csv, outRed)
}
```

### Traitement

```{r traitement}
write("title;slices;min;max", outBlue, append = FALSE)
# write("title;slices;min;max", outRed, append = FALSE)

apply(dfBlue, 1, cropB)
# apply(dfRed, 1, cropR)
```

```{r clear}
close(outBlue)
# close(outRed)
```



```{r stack les moins lumineux}
fillList <- function(liste,max){
  len <- length(liste)
  if (len < max){
    lg <- max-len
    suite <- c(rep.int(c(NA),lg))
    liste <- c(liste,suite)
  }
  return(liste)
}

#minMax <- t(data.frame(apply(dfBlue, 1, cropB)))
dfBlueCrp <- data.frame()
for (i in 1:864) {
  dfBlueCrp[i] <- dfBlue[seq(minMax[i,1],minMax[i,2],1)+2]
}

```



```{r fun2.1}
prep_ridgesplot <- function(df1){
  df1$name <- gsub("jul","",df1$name)
  df1$name <- gsub(".tif","",df1$name)
  
  df1[is.na(df1)] <- -1
  names <- df1[,1]
  rownames(df1) <- names
  df1 <- df1[,-c(1,2)]
  
  len <- length(df1[1,])
  name <- c()
  slice <- c()
  values <- c()
  for (i in 1:length(df1[,1])) {
    name[(i*len-(len-1)):(i*len)] <- names[i]
    slice[(i*len-(len-1)):(i*len)] <- 1:len
    for (j in 1:len) values[((i-1)*len)+j] <- df1[i,j]
  }
  return(data.frame(name,slice,values))
}
```


```{r fun2.2}

endLast <- function(array){
  array <- rev(array)
  last <- array[1,1]
  i=1
  while (last<=0){
    i <- i+1
    last <- array[1,i]
  }
  return(last)
}

supprBorne <- function(array,max,asc){
  ret <- c()
  array[is.na(array)]<- -1
  len <- length(array)
  if (asc) {
    i = 1
    while (array[,i]<max*0.5) {
      ret = c(ret,i+2)
      i <- i+1
    }
  }
  else{
    i = len
    while (array[,i]<max*0.5) {
      ret = c(ret,i+2)
      i <- i-1
    }
  }
  return(ret)
}

takeSlopeAway <- function(df1){
  df1[is.na(df1)] <- -1
  for (i in c(1:length(df1[,1]))) {
    i <- as.numeric(i)
    start <- df1[i,3]
    end <- endLast(df1[i,-c(1,2)])
    maxi <- max(df1[i,-c(1,2)])
    if(start<end){
      maxTH <- end
      asc <- TRUE
    }
    else{
      maxTH<- start
      asc <- FALSE
    }
    if(maxi>maxTH*1.1){
      lst <- supprBorne(df1[i,-c(1,2)],maxTH,asc)
      for(j in lst) df1[i,j] <- -1
    }
  }
  return(df1)
}

```

```{r sep indiv}
xLuj_21 <- takeSlopeAway(dfBlue[grep("jul21_LuJ_", dfBlue$name),])
xLuv_21 <- takeSlopeAway(dfBlue[grep("jul21_LuV_", dfBlue$name),])
xMalu_21 <- takeSlopeAway(dfBlue[grep("jul21_MaLu_", dfBlue$name),])
xLuj_22 <- takeSlopeAway(dfBlue[grep("jul22_LuJ_", dfBlue$name),])
xLuv_22 <- takeSlopeAway(dfBlue[grep("jul22_LuV_", dfBlue$name),])
xMalu_22 <- takeSlopeAway(dfBlue[grep("jul22_MaLu_", dfBlue$name),])
xLuj_22R <- takeSlopeAway(dfBlue[grep("jul22_LuJR_", dfBlue$name),])
xLuv_22R <- takeSlopeAway(dfBlue[grep("jul22_LuVR_", dfBlue$name),])
xMalu_22R <- takeSlopeAway(dfBlue[grep("jul22_MaLuR_", dfBlue$name),])

name <- c()
slice <- c()
value <- c()

Luj_21 <- prep_ridgesplot(xLuj_21)
Luv_21 <- prep_ridgesplot(xLuv_21)
Malu_21 <- prep_ridgesplot(xMalu_21)
Luj_22 <- prep_ridgesplot(xLuj_22)
Luv_22 <- prep_ridgesplot(xLuv_22)
Malu_22 <- prep_ridgesplot(xMalu_22)
Luj_22R <- prep_ridgesplot(xLuj_22R)
Luv_22R <- prep_ridgesplot(xLuv_22R)
Malu_22R <- prep_ridgesplot(xMalu_22R)


```

```{r fig.height = 150, fig.width = 80 }

p1 <- ggplot(Luj_21, aes(x = slice, y = name, height = values, fill=name) ) + geom_ridgeline(scale=0.02, alpha = 0.5, show.legend = FALSE)
p2 <- ggplot(Luv_21, aes(x = slice, y = name, height = values, fill=name) ) + geom_ridgeline(scale=0.02, alpha = 0.5, show.legend = FALSE)
p3 <- ggplot(Malu_21, aes(x = slice, y = name, height = values, fill=name) ) + geom_ridgeline(scale=0.02, alpha = 0.5, show.legend = FALSE)
p4 <- ggplot(Luj_22, aes(x = slice, y = name, height = values, fill=name) ) + geom_ridgeline(scale=0.02, alpha = 0.5, show.legend = FALSE)
p5 <- ggplot(Luv_22, aes(x = slice, y = name, height = values, fill=name) ) + geom_ridgeline(scale=0.02, alpha = 0.5, show.legend = FALSE)
p6 <- ggplot(Malu_22, aes(x = slice, y = name, height = values, fill=name) ) + geom_ridgeline(scale=0.02, alpha = 0.5, show.legend = FALSE)
p7 <- ggplot(Luj_22R, aes(x = slice, y = name, height = values, fill=name) ) + geom_ridgeline(scale=0.02, alpha = 0.5, show.legend = FALSE)
p8 <- ggplot(Luv_22R, aes(x = slice, y = name, height = values, fill=name) ) + geom_ridgeline(scale=0.02, alpha = 0.5, show.legend = FALSE)
p9 <- ggplot(Malu_22R, aes(x = slice, y = name, height = values, fill=name) ) + geom_ridgeline(scale=0.02, alpha = 0.5, show.legend = FALSE)

grid.arrange(p1,p2,p3,p4,p5,p6,p7,p8,p9,nrow = 1)
```

### Test pour bon fonctionnement

```{r test}
data <- data.frame(test = 1:5, y = rep(1, 5), height = c(0, 1, 3, 4, 2))
ggplot(data, aes(test, y, height = height)) + geom_ridgeline()

# data <- data.frame(
#   x = rep(1:5, 3),
#   y = c(rep(0, 5), rep(1, 5), rep(2, 5)),
#   height = c(0, 1, 3, 4, 0, 1, 2, 3, 5, 4, 0, 5, 4, 4, 1)
# )
# t1 <- c(1,2,3,4,5,6,7,8,9,10)
# t2 <- c(1,3,9,4,5,6,7,8,10,2)
# t3 <- c(3,2,10,4,5,6,7,8,1,2)
# 
# r1 <- indexMinSlices(na.omit(t1),3)
# r2 <- indexMinSlices(na.omit(t2),3)
# r3 <- indexMinSlices(na.omit(t3),3)
# cat("res1=",r1,"res2=",r2,"res3=",r3)

# write.csv("test", outputBlue, append = TRUE, sep=';', row.names = FALSE, col.names = FALSE)
```
